# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'better_signatureui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TEXT = QtWidgets.QTextBrowser(self.centralwidget)
        self.TEXT.setGeometry(QtCore.QRect(80, 10, 891, 81))
        self.TEXT.setAutoFillBackground(False)
        self.TEXT.setObjectName("TEXT")
        self.CHECK = QtWidgets.QPushButton(self.centralwidget)
        self.CHECK.setGeometry(QtCore.QRect(10, 380, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CHECK.setFont(font)
        self.CHECK.setObjectName("CHECK")
        self.SHOW = QtWidgets.QPushButton(self.centralwidget)
        self.SHOW.setGeometry(QtCore.QRect(10, 310, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SHOW.setFont(font)
        self.SHOW.setCheckable(False)
        self.SHOW.setObjectName("SHOW")
        self.idSelector = QtWidgets.QComboBox(self.centralwidget)
        self.idSelector.setGeometry(QtCore.QRect(230, 150, 91, 41))
        self.idSelector.setObjectName("idSelector")
        self.id_text = QtWidgets.QLabel(self.centralwidget)
        self.id_text.setGeometry(QtCore.QRect(200, 120, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_text.setFont(font)
        self.id_text.setObjectName("id_text")
        self.imglabel = QtWidgets.QLabel(self.centralwidget)
        self.imglabel.setGeometry(QtCore.QRect(180, 370, 371, 281))
        self.imglabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imglabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imglabel.setLineWidth(7)
        self.imglabel.setText("")
        self.imglabel.setObjectName("imglabel")
        self.captured_img = QtWidgets.QLabel(self.centralwidget)
        self.captured_img.setGeometry(QtCore.QRect(600, 370, 371, 281))
        self.captured_img.setFrameShape(QtWidgets.QFrame.Box)
        self.captured_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.captured_img.setLineWidth(7)
        self.captured_img.setText("")
        self.captured_img.setObjectName("captured_img")
        self.captured_img_text = QtWidgets.QLabel(self.centralwidget)
        self.captured_img_text.setGeometry(QtCore.QRect(740, 340, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.captured_img_text.setFont(font)
        self.captured_img_text.setObjectName("captured_img_text")
        self.test_img = QtWidgets.QLabel(self.centralwidget)
        self.test_img.setGeometry(QtCore.QRect(430, 100, 351, 181))
        self.test_img.setFrameShape(QtWidgets.QFrame.Box)
        self.test_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_img.setLineWidth(7)
        self.test_img.setText("")
        self.test_img.setObjectName("test_img")
        self.live_camera_text = QtWidgets.QLabel(self.centralwidget)
        self.live_camera_text.setGeometry(QtCore.QRect(310, 340, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.live_camera_text.setFont(font)
        self.live_camera_text.setObjectName("live_camera_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CHECK.setText(_translate("MainWindow", "Check"))
        self.SHOW.setText(_translate("MainWindow", "Show"))
        self.id_text.setText(_translate("MainWindow", "You are testing with ID:"))
        self.captured_img_text.setText(_translate("MainWindow", "Captured Image:"))
        self.live_camera_text.setText(_translate("MainWindow", "Live Camera : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
